### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by mseri**
I noticed a number of warnings and an erroneous failure when building with ocaml 4.10.0.

To resolve the issue, instead of figuring out how to modify the oasis/ocamlbuild files I have ported plplot to dune2 (and with the occasion to opam2).

### CODE REVIEW

**Comment by hcarty** [comment]
This is fantastic, thank you!  Any issue with merging this now, or do you have more you want to do before that?

**Comment by mseri** [comment]
Wait a bit. I am trying to test it, and currently get a weird stubs linking error
```
ld: library not found for -lplplot_stubs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mseri** [comment]
I think it was an issue in my tests dune file (I was integrating a few ODEs and plotting the results with `owl-plplot`), I cannot reproduce it any longer. I think it should be safe to merge

**Comment by mseri** [comment]
I take it back, for some reason that I don't understand. I have one example, and only one, using both plplot and odepack, that works in native mode but fails to compile in bytecode mode. All other examples work fine in both modes. I truly have no idea of the reason...

**Comment by mseri** [comment]
@hcarty this is now good to merge imo

**Comment by hcarty** [comment]
Thank you again!

**Pull request merged**
